In [25]:
import numpy as np

In [26]:
x=np.array([[0,0],[0,1],[1,0],[1,1]]) #And 
y=np.array([[0,1,1,0]]).T
x.shape,y.shape

((4, 2), (4, 1))

In [27]:
def sig(z):
    return(1/(1+np.exp(-z)))
sig(0)

0.5

In [28]:
def derivativesig(z):
    return sig(z)*(1-sig(z))

In [29]:
wh = 2*np.random.random((2,2))-1# 2 feature 2 unit in next layer
bh = 2*np.random.random((1,2))-1# 1 baised 2 unit in next layer 
wo = 2*np.random.random((2,1))-1# 2 unit in current layer 1 unit in next layer (output])
bo = 2*np.random.random((1,1))-1# 1 baised 1 unit
lr=1

In [30]:
output0 = x
outputHidden = sig(np.dot(output0,wh)+bh)# output0 is 4*2 and weight is 2*2= 4*2 and then we add bais 
output= sig(np.dot(outputHidden,wo)+bo)
output

array([[0.75155588],
       [0.72073004],
       [0.7294207 ],
       [0.69550582]])

In [31]:
x=np.array([[0,0],[0,1],[1,0],[1,1]]) #And 
y=np.array([[0,1,1,0]]).T

In [40]:
for i in range (10000):
    output0 = x
    inputhidden=np.dot(output0,wh)+bh
    outputhidden=sig(inputhidden)
    inputforoutputlayer=np.dot(outputhidden,wo)+bo# output0 is 4*2 and weight is 2*2= 4*2 and then we add bais 
    output= sig(inputforoutputlayer)

    first_term_output_layer=output - y
    second_term_output_layer=derivativesig(inputforoutputlayer)
    first_second_term_output_layer=first_term_output_layer*second_term_output_layer

    first_term_hidden_layer=np.dot(first_second_term_output_layer,wo.T)
    second_term_hidden_layer=derivativesig(inputhidden)
    first_second_term_hidden_layer=first_term_hidden_layer*second_term_hidden_layer
    

    changes_outputlayer=np.dot(outputhidden.T,first_second_term_output_layer)
    changes_baised_outputlayer=np.sum(first_second_term_output_layer,axis=0,keepdims=True)

    changes_hiddenlayer=np.dot(output0.T,first_second_term_hidden_layer)
    changes_baised_hiddenlayer=np.sum(first_second_term_hidden_layer,axis=0,keepdims=True)

    wo = wo - lr*changes_outputlayer
    bo = bo - lr*changes_baised_outputlayer

    wh = wh - lr*changes_hiddenlayer
    bh = bh - lr*changes_baised_hiddenlayer
    
output0 = x
inputhidden=np.dot(output0,wh)+bh
outputhidden=sig(inputhidden)
inputforoutputlayer=np.dot(outputhidden,wo)+bo# output0 is 4*2 and weight is 2*2= 4*2 and then we add bais 
output= sig(inputforoutputlayer)
print("--------------\n output \n--------------\n",output,"\n-----------------\n weights hidden\n-----------------\n",wh,"\n--------------\n baised hidden\n--------------\n",bh,"\n---------------\n weights output \n-------------\n",wo,"\n----------------\n baised output\n----------------\n",bo)

--------------
 output 
--------------
 [[0.00342654]
 [0.99649073]
 [0.99649038]
 [0.00429535]] 
-----------------
 weights hidden
-----------------
 [[-6.08250369 -6.7713467 ]
 [-6.0830387  -6.77296445]] 
--------------
 baised hidden
--------------
 [[9.08683446 2.86218221]] 
---------------
 weights output 
-------------
 [[ 12.48622414]
 [-12.8576634 ]] 
----------------
 baised output
----------------
 [[-5.99494241]]
