In [1]:
import numpy as np

In [2]:
x=np.array([[0,0],[0,1],[1,0],[1,1]]) #And 
y=np.array([[0,0,0,1]]).T
x.shape,y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return(1/(1+np.exp(-z)))
sig(0)

0.5

In [4]:
def derivativesig(z):
    return sig(z)*(1-sig(z))

In [8]:
#NO HIDDEN LAYER WEIGHTS
#it only gives positives#weights = np.random.random((2,1))
weights = 2*np.random.random((2,1))-1# to change range from -1 to 1
bias= 2 * np.random.random(1)-1
lr=0.1
datapoints=x.shape[0]
features=x.shape[1]
weights,bias

(array([[0.09665188],
        [0.96032325]]),
 array([-0.94203693]))

In [9]:
# FORWARD PROPAGATION WITHOUT ANY HIDDEN LAYER
for iter in range(10000):
    output0 = x 
    output = sig(np.dot(output0,weights)+bias)#vector dot product

    first_term = output - y
    input_for_last_layer = np.dot(output0,weights)+bias
    second_term = derivativesig(input_for_last_layer)
    first_two = first_term * second_term
    first_two.shape

    changes=np.array([[0.0],[0.0]])
    for i in range(features):
        for j in range(datapoints):
            changes[i][0] += first_two[j][0]*output0[j][i]
  
    bias_change = 0.0
    for j in range(datapoints):
        bias_change += first_two[j][0]*1

    weights= weights - lr*changes
    bias   = bias    - lr*bias_change
output=sig(np.dot(x,weights)+bias)
weights,bias,output

(array([[5.48676281],
        [5.48676284]]),
 array([-8.32280382]),
 array([[2.42854828e-04],
        [5.54073781e-02],
        [5.54073766e-02],
        [9.34055466e-01]]))